### ISSUE TITLE
Is `resource_record` working ? 

### ISSUE THREAD

**Issue by pfrayer** [kenyon/puppet-bind#18]
Hello :wave: 

After playing with this module, I struggled to have records created using `resource_record`. 
I tried to used the same example as in [this test](https://github.com/kenyon/puppet-bind/blob/main/spec/acceptance/bind_authoritative_spec.rb#L12-L49), but no actual records are created.

After checking the code [here](https://github.com/kenyon/puppet-bind/blob/main/lib/puppet/provider/resource_record/resource_record.rb#L21-L31), it seems the `resource_record` is not implemented yet ? 

If so, it could be nice to mention this in the doc, as currently nothing mention this yet (or maybe I missed it ?) :)

**Comment by kenyon** [comment]
Right, it hasn't been implemented yet. The acceptance test fails: https://github.com/kenyon/puppet-bind/actions/runs/5993778963/job/16254558214

#14 implements it, but without tests, so I didn't merge that.

I don't run BIND anymore, so I don't work on this module anymore, but I'm happy to merge pull requests if they include tests.
